Controllers/ChessController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;

namespace ChessApp.Controllers
{
    public class ChessController : Controller
    {
        static List<Models.ChessMatch> _MatchList = new();
        static int _MatchCounter = 1;
        public IActionResult Index()
        {
            return View();
        }
        //also used to request ongoing match by giving an id on the request
        public IActionResult StartMatch(int _Id = -1)
        {
            Trace.WriteLine("------ DEBUG ------");
            Trace.WriteLine($"IActionResult StartMatch with id: {_Id}");
            if (_Id < 0)
            {
                Trace.WriteLine("creating new match");
                Trace.WriteLine(_MatchList.Count);
                _MatchList.Add(new(_MatchCounter));
                Trace.WriteLine(_MatchList.Count);
                Trace.WriteLine("new match created");
                _Id = _MatchCounter;
                _MatchCounter++;
            }
            List<Models.ChessMatch> MatchList = _MatchList;
            foreach (Models.ChessMatch match in MatchList)
            {
                if (_Id == match.Id)
                {
                    Trace.WriteLine(JsonConvert.SerializeObject(match));
                    Trace.WriteLine("Json away");
                    Trace.WriteLine("------  END  ------");
                    return Json(JsonConvert.SerializeObject(match));
                }
            }
            return Content("Error");
        }
        [HttpPost]
        public IActionResult Move(string _move)
        {
            Trace.WriteLine("------ DEBUG ------");
            Trace.WriteLine("IActionResult Move");
            Trace.WriteLine($"Matches in MatchList: {_MatchList.Count}");
            Trace.WriteLine($"json received: {_move}");
            Models.Move Movement;
            try
            { 
                Movement = JsonConvert.DeserializeObject<Models.Move>(_move);
            }
            catch
            {
                Trace.WriteLine("json error");
                return Content("Error: json parce error");
            }
            Trace.WriteLine("json - ok, validating");
            Trace.WriteLine("comparing ids");
            Trace.WriteLine(_MatchList.Count);
            List<Models.ChessMatch> MatchList = _MatchList;
            int matchNumber = 0;
            foreach (Models.ChessMatch Match in MatchList)
            {
                Trace.WriteLine($"{Match.Id} | {Movement.Id}");
                if(Match.Id == Movement.Id)
                {
                    if (Match.Move(Movement))
                    {
                        Trace.WriteLine("movement made");
                        Trace.WriteLine("overwriting:");
                        foreach (List<string> row in _MatchList[matchNumber].Board)
                        {
                            string rowReturn = "<";
                            foreach (string col in row)
                            {
                                if (rowReturn != "<") { rowReturn += ";"; };
                                if (col == "") { rowReturn += "__"; }
                                else { rowReturn += col; }
                            }
                            rowReturn += ">";
                            Trace.WriteLine(rowReturn);
                        }
                        Trace.WriteLine("with:");
                        foreach (List<string> row in Match.Board)
                        {
                            string rowReturn = "<";
                            foreach (string col in row)
                            {
                                if (rowReturn != "<") { rowReturn += ";"; };
                                if (col == "") { rowReturn += "__"; }
                                else { rowReturn += col; }
                            }
                            rowReturn += ">";
                            Trace.WriteLine(rowReturn);
                        }
                        _MatchList[matchNumber] = Match;
                        Trace.WriteLine("result:");
                        foreach (List<string> row in _MatchList[matchNumber].Board)
                        {
                            string rowReturn = "<";
                            foreach (string col in row)
                            {
                                if (rowReturn != "<") { rowReturn += ";"; }
                                if (col == "") { rowReturn += "__"; }
                                else { rowReturn += col; }
                            }
                            rowReturn += ">";
                            Trace.WriteLine(rowReturn);
                        }
                    }
                    else { Trace.WriteLine("movement not made"); }
                    return Content("Success");
                }
                matchNumber++;
            }
            return Content("Error: id not found");
            }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ChessApp.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChessApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChessApp.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/chess.css">
    <script type="text/javascript" src='http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChessApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Chess" asp-action="Index">Chess</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
                <div class="btn-group dropstart">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Login
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="padding: 15px; padding-bottom: 10px;">
                        <form class="form-horizontal" method="post" accept-charset="UTF-8">
                            <input class="form-control login" type="text" name="username" placeholder="Username.."><br>
                            <input class="form-control login" type="password" name="password" placeholder="Password.."><br>
                            <input class="btn btn-primary" type="submit" name="submit" value="Login">
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChessApp
        </div>
    </footer>

    <script src="~/js/chess.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>